version: "3.9"

services:
  caddy:
    image: zthedev/mycaddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./html:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
